spring:
  application:
    name: UserPortfoliosService
  data:
    mongodb:
      database: UserDB
#      port: ${mongoport}
#      host: ${mongohost}
#      username: ${mongouser}
#      password: ${mongopass}
      port: 27017
      host: localhost
#      username: ${mongouser}
#      password: ${mongopass}
  feign:
    clients:
      tinkoff-service:
        url: http://localhost:8082/api/v1

server:
  port: 8085