spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      schema-locations: schema.sql
      data-locations: data.sql
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update