spring:
  messages:
    encoding: UTF-8

  datasource:
    url: jdbc:h2:mem:security

  sql:
    init:
      mode: always

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: update

    show-sql: true

logging:
  level:
    ROOT: INFO